# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwK60JyKhZ1saxivkCdhaU-BGlCXnLQ3
"""

import pandas as pd
import numpy as np

import pickle
import streamlit as st
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

def input_features():

  dt_home = st.number_input('Enter the distance from home to transaction occured:')
  dt_transac = st.number_input('Enter the distance from last transaction happened:')
  rt_price = st.number_input('Enter the price to median price ratio of transaction:')
  try:
    repeat_rt = st.number_input('was the retailer same? write 1(yes) and 0(no):')
    used_chip = st.number_input('was the chip used? write 1(yes) and 0(no):')
    used_pin = st.number_input('was the pin used? write 1(yes) and 0(no):')
    online_order = st.number_input('was the online order used? write 1(yes) and 0(no):')
  except ValueError:
    st.error('Please enter value in number.')

  data = {
      'dt_home' : dt_home,
      'dt_transac' : dt_transac,
      'rt_price' : rt_price,
      'repeat_rt' : repeat_rt,
      'used_chip' : used_chip,
      'used_pin' : used_pin,
      'online_order' : online_order
  }
  features = pd.DataFrame(data, index = [0])

  return features

st.title("Credit Fraud Detection")

input_df = input_features()

model = pickle.load(open(r'/content/xgb_model.pkl', 'rb'))

input_scaled = std_scaler.fit_transform(input_df)

if st.button('Predict'):
  try:
    prediction = model.predict(input_scaled)
    probability = model.predict_proba(input_scaled)
  except:
    st.error('Error occured during prediction..!!')

  st.subheader('Prediction')

  if prediction == 0:
    st.write('The transaction is not fraud.')
  else:
    st.write('The transaction is fraud.')

  st.header('Probability')

  if prediction == 0:
    st.write(f'Probability: {probability[0][0]: 0.3f}')
  else:
    st.write(f'Probability: {probability[0][1]: 0.3f}')